[package]
name = "rust_3d"
version = "0.1.0"
authors = ["Martin Hedberg <96mah002@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
